// Mock Data: Articles - KynguyenAI v3.0
// 25+ bài viết đa dạng categories

import type { Article } from "@/types";

export const mockArticles: Article[] = [
  // ============ FEATURED / HERO ARTICLES ============
  {
    id: "art-001",
    url_hash: "a1b2c3d4e5f6",
    title_hash: "f6e5d4c3b2a1",
    title_vi: "OpenAI ra mắt GPT-5: Bước đột phá mới trong AI với khả năng reasoning vượt trội",
    summary_vi: "GPT-5 đánh dấu bước tiến lớn trong lĩnh vực AI với khả năng suy luận đa bước, hiểu ngữ cảnh sâu hơn và giải quyết vấn đề phức tạp. Model mới có thể xử lý các tác vụ cần tư duy logic như lập kế hoạch, coding và phân tích dữ liệu với độ chính xác cao hơn 40% so với GPT-4.",
    original_url: "https://openai.com/blog/gpt-5",
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800",
    category: "AI News",
    source: "TLDR AI",
    published_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 giờ trước
    tile_size: "hero",
    is_featured: true,
    status: "published",
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-002",
    url_hash: "b2c3d4e5f6a1",
    title_hash: "a1f6e5d4c3b2",
    title_vi: "Claude 4 Opus đạt điểm cao nhất trên benchmark MMLU-Pro và HumanEval",
    summary_vi: "Anthropic công bố Claude 4 Opus với điểm số vượt trội trên các benchmark quan trọng. Model mới đạt 92.3% trên MMLU-Pro, vượt GPT-4 Turbo và Gemini Ultra. Đặc biệt, Claude 4 Opus đạt 95.1% trên HumanEval cho code generation.",
    original_url: "https://anthropic.com/claude-4",
    thumbnail: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800",
    category: "AI News",
    source: "AlphaSignal",
    published_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    tile_size: "hero",
    is_featured: true,
    status: "published",
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },

  // ============ AI NEWS ============
  {
    id: "art-003",
    url_hash: "c3d4e5f6a1b2",
    title_hash: "b2a1f6e5d4c3",
    title_vi: "Google DeepMind ra mắt Gemini 2.0 với khả năng multimodal native",
    summary_vi: "Gemini 2.0 là model AI đầu tiên được thiết kế từ đầu với khả năng xử lý đa phương thức, có thể hiểu và tạo nội dung text, image, audio và video trong một kiến trúc thống nhất.",
    original_url: "https://deepmind.google/gemini-2",
    thumbnail: "https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=800",
    category: "AI News",
    source: "The Rundown AI",
    published_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    tile_size: "tall",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-004",
    url_hash: "d4e5f6a1b2c3",
    title_hash: "c3b2a1f6e5d4",
    title_vi: "Meta phát hành Llama 4 với 400B parameters - Mô hình open source mạnh nhất",
    summary_vi: "Meta tiếp tục cam kết với AI mở nguồn, phát hành Llama 4 với 400 tỷ parameters. Model mới cạnh tranh trực tiếp với các model closed-source hàng đầu và được tối ưu cho việc fine-tuning.",
    original_url: "https://ai.meta.com/llama-4",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800",
    category: "AI News",
    source: "TLDR AI",
    published_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-005",
    url_hash: "e5f6a1b2c3d4",
    title_hash: "d4c3b2a1f6e5",
    title_vi: "Microsoft tích hợp Copilot sâu vào Windows 12 với AI Agent capabilities",
    summary_vi: "Windows 12 sẽ có Copilot được tích hợp ở cấp hệ điều hành, cho phép điều khiển máy tính bằng ngôn ngữ tự nhiên, tự động hóa workflow và hỗ trợ context-aware theo ứng dụng đang sử dụng.",
    original_url: "https://microsoft.com/windows-12-copilot",
    thumbnail: "https://images.unsplash.com/photo-1624996379697-f01d168b1a52?w=800",
    category: "AI News",
    source: "The Rundown AI",
    published_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 19 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-006",
    url_hash: "f6a1b2c3d4e5",
    title_hash: "e5d4c3b2a1f6",
    title_vi: "Apple Intelligence 2.0 hỗ trợ tiếng Việt và 15 ngôn ngữ mới",
    summary_vi: "Apple mở rộng Apple Intelligence đến nhiều ngôn ngữ hơn, bao gồm tiếng Việt. Người dùng iPhone 16 tại Việt Nam sẽ có thể sử dụng Siri AI, Writing Tools và Image Generation bằng tiếng Việt.",
    original_url: "https://apple.com/apple-intelligence",
    thumbnail: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800",
    category: "AI News",
    source: "TLDR AI",
    published_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    tile_size: "wide",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-007",
    url_hash: "a2b3c4d5e6f7",
    title_hash: "f7e6d5c4b3a2",
    title_vi: "NVIDIA H200 GPU: Hiệu năng AI training tăng 2x so với H100",
    summary_vi: "NVIDIA công bố H200 với 141GB HBM3e memory và bandwidth 4.8TB/s. GPU mới giúp training large language models nhanh gấp đôi và giảm chi phí inference đáng kể cho các AI workloads.",
    original_url: "https://nvidia.com/h200",
    thumbnail: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800",
    category: "AI News",
    source: "AlphaSignal",
    published_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 31 * 60 * 60 * 1000).toISOString(),
  },

  // ============ AI TOOLS ============
  {
    id: "art-008",
    url_hash: "b3c4d5e6f7a2",
    title_hash: "a2f7e6d5c4b3",
    title_vi: "10 công cụ AI miễn phí tốt nhất cho Developer năm 2026",
    summary_vi: "Danh sách tổng hợp các công cụ AI hữu ích cho lập trình viên: từ GitHub Copilot miễn phí cho student, đến Cursor IDE, Codeium, và các tool debugging AI-powered. Tất cả đều có free tier đủ dùng.",
    original_url: "https://dev.to/ai-tools-2026",
    thumbnail: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800",
    category: "AI Tools",
    source: "AlphaSignal",
    published_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    tile_size: "tall",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-009",
    url_hash: "c4d5e6f7a2b3",
    title_hash: "b3a2f7e6d5c4",
    title_vi: "Perplexity ra mắt tính năng Deep Research cho phân tích chuyên sâu",
    summary_vi: "Perplexity Deep Research có thể thực hiện nghiên cứu kéo dài nhiều phút, tổng hợp hàng trăm nguồn và tạo báo cáo chi tiết. Tính năng mới cạnh tranh trực tiếp với các research assistant trả phí.",
    original_url: "https://perplexity.ai/deep-research",
    thumbnail: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=800",
    category: "AI Tools",
    source: "The Rundown AI",
    published_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-010",
    url_hash: "d5e6f7a2b3c4",
    title_hash: "c4b3a2f7e6d5",
    title_vi: "Midjourney v7: Tạo hình ảnh với độ chi tiết và consistency chưa từng có",
    summary_vi: "Midjourney v7 mang đến chất lượng hình ảnh photorealistic, character consistency giữa các prompt, và khả năng edit chi tiết. Model mới cũng hỗ trợ tạo video ngắn 3-5 giây.",
    original_url: "https://midjourney.com/v7",
    thumbnail: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800",
    category: "AI Tools",
    source: "TLDR AI",
    published_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-011",
    url_hash: "e6f7a2b3c4d5",
    title_hash: "d5c4b3a2f7e6",
    title_vi: "Cursor 2.0: IDE AI-native với multi-agent collaboration",
    summary_vi: "Cursor 2.0 giới thiệu tính năng multiple AI agents làm việc song song trên codebase. Agents có thể phân chia task, review code của nhau và giải quyết conflicts tự động.",
    original_url: "https://cursor.sh/2.0",
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800",
    category: "AI Tools",
    source: "AlphaSignal",
    published_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    tile_size: "wide",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 37 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-012",
    url_hash: "f7a2b3c4d5e6",
    title_hash: "e6d5c4b3a2f7",
    title_vi: "Notion AI 3.0: Workspace assistant hiểu toàn bộ knowledge base",
    summary_vi: "Notion AI 3.0 có thể truy cập và hiểu toàn bộ workspace, đưa ra gợi ý dựa trên context từ hàng nghìn trang. Tính năng mới bao gồm auto-linking, smart templates và meeting summaries.",
    original_url: "https://notion.so/ai-3",
    thumbnail: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800",
    category: "AI Tools",
    source: "The Rundown AI",
    published_at: new Date(Date.now() - 42 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 43 * 60 * 60 * 1000).toISOString(),
  },

  // ============ AI TUTORIAL ============
  {
    id: "art-013",
    url_hash: "a3b4c5d6e7f8",
    title_hash: "f8e7d6c5b4a3",
    title_vi: "Hướng dẫn Fine-tuning LLM với LoRA và QLoRA từ A-Z",
    summary_vi: "Tutorial chi tiết về cách fine-tune các model như Llama, Mistral sử dụng LoRA adapter. Bao gồm dataset preparation, hyperparameter tuning, và deployment với vLLM. Code mẫu trên Google Colab miễn phí.",
    original_url: "https://huggingface.co/lora-tutorial",
    thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800",
    category: "AI Tutorial",
    source: "Import AI",
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    tile_size: "tall",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-014",
    url_hash: "b4c5d6e7f8a3",
    title_hash: "a3f8e7d6c5b4",
    title_vi: "Xây dựng RAG Application với LangChain và Pinecone",
    summary_vi: "Hướng dẫn xây dựng hệ thống Retrieval-Augmented Generation hoàn chỉnh. Từ indexing documents, chunking strategies, đến semantic search và answer generation với citations.",
    original_url: "https://langchain.com/rag-tutorial",
    thumbnail: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800",
    category: "AI Tutorial",
    source: "AlphaSignal",
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 49 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-015",
    url_hash: "c5d6e7f8a3b4",
    title_hash: "b4a3f8e7d6c5",
    title_vi: "Prompt Engineering nâng cao: Chain-of-Thought và Tree-of-Thoughts",
    summary_vi: "Deep dive vào các kỹ thuật prompting hiệu quả nhất cho reasoning tasks. So sánh CoT, ToT, ReAct và cách kết hợp chúng để giải quyết bài toán phức tạp với LLMs.",
    original_url: "https://lilianweng.github.io/prompt-engineering",
    thumbnail: "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=800",
    category: "AI Tutorial",
    source: "Import AI",
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 73 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-016",
    url_hash: "d6e7f8a3b4c5",
    title_hash: "c5b4a3f8e7d6",
    title_vi: "Deploy AI Model lên Production với vLLM và Kubernetes",
    summary_vi: "Hướng dẫn deploy LLM models với throughput cao sử dụng vLLM engine. Setup Kubernetes cluster, auto-scaling, monitoring và các best practices cho production AI systems.",
    original_url: "https://vllm.ai/production-guide",
    thumbnail: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800",
    category: "AI Tutorial",
    source: "TLDR AI",
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 97 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-017",
    url_hash: "e7f8a3b4c5d6",
    title_hash: "d6c5b4a3f8e7",
    title_vi: "Building AI Agents với LangGraph: From Zero to Hero",
    summary_vi: "Tutorial toàn diện về xây dựng AI Agents có khả năng planning, tool use và memory. Sử dụng LangGraph để tạo agent graphs phức tạp với multi-step reasoning.",
    original_url: "https://langchain.com/langgraph-agents",
    thumbnail: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800",
    category: "AI Tutorial",
    source: "AlphaSignal",
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tile_size: "wide",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 121 * 60 * 60 * 1000).toISOString(),
  },

  // ============ AI VIETNAM (NEW CATEGORY) ============
  {
    id: "art-018",
    url_hash: "f8a3b4c5d6e7",
    title_hash: "e7d6c5b4a3f8",
    title_vi: "VinAI ra mắt PhoGPT-4: Model tiếng Việt đạt benchmark quốc tế",
    summary_vi: "VinAI Research công bố PhoGPT-4, model ngôn ngữ lớn đầu tiên của Việt Nam đạt điểm ngang ngửa với GPT-3.5 trên các benchmark tiếng Việt. Model sẽ được open-source cho cộng đồng nghiên cứu.",
    original_url: "https://vinai.io/phogpt-4",
    thumbnail: "https://images.unsplash.com/photo-1583521214690-73421a1829a9?w=800",
    category: "AI News",
    source: "TLDR AI",
    published_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    tile_size: "tall",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-019",
    url_hash: "a4b5c6d7e8f9",
    title_hash: "f9e8d7c6b5a4",
    title_vi: "FPT AI triển khai AI Agent cho 10 ngân hàng lớn tại Việt Nam",
    summary_vi: "FPT công bố hợp tác với 10 ngân hàng để triển khai AI Agent phục vụ khách hàng 24/7. Hệ thống xử lý tiếng Việt tự nhiên và tích hợp sâu với core banking systems.",
    original_url: "https://fpt.ai/banking-agents",
    thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800",
    category: "AI News",
    source: "AlphaSignal",
    published_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 49 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-020",
    url_hash: "b5c6d7e8f9a4",
    title_hash: "a4f9e8d7c6b5",
    title_vi: "Khóa học AI miễn phí từ Google dành cho người Việt",
    summary_vi: "Google hợp tác với Bộ Giáo dục Việt Nam ra mắt chương trình đào tạo AI miễn phí. Khóa học bao gồm Machine Learning cơ bản, Generative AI và Applied AI với chứng chỉ quốc tế.",
    original_url: "https://grow.google/ai-vietnam",
    thumbnail: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800",
    category: "AI Tutorial",
    source: "The Rundown AI",
    published_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 73 * 60 * 60 * 1000).toISOString(),
  },

  // ============ MORE ARTICLES ============
  {
    id: "art-021",
    url_hash: "c6d7e8f9a4b5",
    title_hash: "b5a4f9e8d7c6",
    title_vi: "Stability AI phát hành Stable Diffusion 4 với kiến trúc DiT mới",
    summary_vi: "Stable Diffusion 4 sử dụng Diffusion Transformer architecture, tạo hình ảnh với độ phân giải 4K và coherence vượt trội. Model mới cũng hỗ trợ inpainting và outpainting tốt hơn nhiều.",
    original_url: "https://stability.ai/sd4",
    thumbnail: "https://images.unsplash.com/photo-1634017839464-5c339bbe3c35?w=800",
    category: "AI News",
    source: "TLDR AI",
    published_at: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-022",
    url_hash: "d7e8f9a4b5c6",
    title_hash: "c6b5a4f9e8d7",
    title_vi: "Suno v4: Tạo nhạc AI với chất lượng studio recording",
    summary_vi: "Suno v4 có thể tạo bài hát hoàn chỉnh với vocals, instruments và mixing chuyên nghiệp. Model mới hỗ trợ nhiều thể loại nhạc hơn và cho phép control chi tiết từng track.",
    original_url: "https://suno.ai/v4",
    thumbnail: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800",
    category: "AI Tools",
    source: "The Rundown AI",
    published_at: new Date(Date.now() - 54 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 55 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-023",
    url_hash: "e8f9a4b5c6d7",
    title_hash: "d7c6b5a4f9e8",
    title_vi: "Runway Gen-3 Alpha: Video AI 10 giây với motion control chính xác",
    summary_vi: "Runway Gen-3 Alpha cho phép tạo video AI với camera movement control, character consistency và text-to-video chất lượng cao. Tính năng mới là multi-shot generation giữ nhất quán nhân vật.",
    original_url: "https://runway.ml/gen3-alpha",
    thumbnail: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800",
    category: "AI Tools",
    source: "AlphaSignal",
    published_at: new Date(Date.now() - 60 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 61 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-024",
    url_hash: "f9a4b5c6d7e8",
    title_hash: "e8d7c6b5a4f9",
    title_vi: "ElevenLabs Voice Cloning: Tạo giọng nói AI chỉ với 30 giây audio",
    summary_vi: "ElevenLabs cải tiến voice cloning technology, chỉ cần 30 giây audio sample để tạo giọng nói AI tự nhiên. Hỗ trợ 30+ ngôn ngữ bao gồm tiếng Việt với độ chính xác cao.",
    original_url: "https://elevenlabs.io/voice-cloning",
    thumbnail: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800",
    category: "AI Tools",
    source: "TLDR AI",
    published_at: new Date(Date.now() - 78 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 79 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "art-025",
    url_hash: "a5b6c7d8e9f0",
    title_hash: "f0e9d8c7b6a5",
    title_vi: "Hướng dẫn tối ưu inference LLM với Flash Attention 3",
    summary_vi: "Deep dive vào Flash Attention 3 và cách sử dụng để giảm 50% memory footprint và tăng 2x throughput cho LLM inference. Bao gồm benchmark và implementation guide chi tiết.",
    original_url: "https://github.com/Dao-AILab/flash-attention",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800",
    category: "AI Tutorial",
    source: "Import AI",
    published_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    tile_size: "standard",
    is_featured: false,
    status: "published",
    created_at: new Date(Date.now() - 145 * 60 * 60 * 1000).toISOString(),
  },
];

// Helper function to get articles by filter
export function getMockArticles(options: {
  limit?: number;
  offset?: number;
  category?: string;
  featured?: boolean;
} = {}): { data: Article[]; total: number } {
  const { limit = 20, offset = 0, category, featured } = options;

  let filtered = [...mockArticles];

  if (category) {
    filtered = filtered.filter((a) => a.category === category);
  }

  if (featured !== undefined) {
    filtered = filtered.filter((a) => a.is_featured === featured);
  }

  // Sort by published_at DESC
  filtered.sort(
    (a, b) =>
      new Date(b.published_at).getTime() - new Date(a.published_at).getTime()
  );

  const total = filtered.length;
  const data = filtered.slice(offset, offset + limit);

  return { data, total };
}

// Get single article
export function getMockArticleById(id: string): Article | null {
  return mockArticles.find((a) => a.id === id) || null;
}

// Get featured article
export function getMockFeaturedArticle(): Article | null {
  return mockArticles.find((a) => a.is_featured && a.tile_size === "hero") || null;
}
